# Generated by Django 5.2.15 on 2026-06-08 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='customuser',
            name='saved_jobs',
            field=models.ManyToManyField(blank=True, related_name='saved_by', to='api.job'),
        ),
    ]
