# Generated by Django 5.2.15 on 2026-06-08 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_customuser_location_customuser_saved_jobs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='generated_cv',
        ),
    ]
