# Generated by Django 5.2.15 on 2026-06-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_employeeprofile_generated_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='commission_range',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
