# Generated by Django 5.2.15 on 2026-06-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_job_commission_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='currency',
            field=models.CharField(default='USD', max_length=100),
        ),
    ]
