# Generated by Django 5.2.15 on 2026-06-10 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_job_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='education',
            field=models.TextField(blank=True),
        ),
    ]
