# Generated by Django 5.2.15 on 2026-06-10 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_employeeprofile_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='employment_type',
            field=models.CharField(blank=True, default='Full-time', max_length=100),
        ),
    ]
