# Generated by Django 5.2.15 on 2026-06-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_job_employment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
