# Generated by Django 5.2.15 on 2026-06-11 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
