# Generated by Django 5.2.15 on 2026-06-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_add_savedjob_through_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='appwrite_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='appwrite_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='job',
            name='appwrite_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='appwrite_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
