# Generated by Django 5.2.15 on 2026-06-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_job_company_address_job_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='package',
            field=models.CharField(blank=True, choices=[('pipeline', 'Quota Hire Pipeline'), ('hunters', 'Quota Hire Commission Hunters'), ('sales_ops', 'Quota Hire Sales Ops')], max_length=50),
        ),
    ]
