# Generated by Django 5.2.15 on 2026-06-15 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_job_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortlistedApplicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('interview', 'Interview'), ('decision', 'Decision'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('shortlisted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shortlist', to='api.application')),
            ],
            options={
                'verbose_name': 'Shortlisted Applicant',
                'verbose_name_plural': 'Shortlisted Applicants',
                'ordering': ['-shortlisted_at'],
            },
        ),
    ]
