# Generated by Django 5.2.15 on 2026-06-16 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_shortlistedapplicant'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='resume_binary',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='resume_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
