# Generated by Django 5.2.15 on 2026-06-23 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_employeeprofile_resume_binary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='appwrite_id',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='appwrite_id',
        ),
        migrations.RemoveField(
            model_name='job',
            name='appwrite_id',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='appwrite_id',
        ),
    ]
