# Generated by Django 5.2.15 on 2026-06-24 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_application_appwrite_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_id', models.CharField(max_length=10)),
                ('template_name', models.CharField(max_length=100)),
                ('target_role', models.CharField(blank=True, max_length=200)),
                ('target_company', models.CharField(blank=True, max_length=200)),
                ('cv_pdf', models.BinaryField(blank=True, editable=True, null=True)),
                ('cv_filename', models.CharField(default='cv.pdf', max_length=255)),
                ('cover_letter_text', models.TextField(blank=True)),
                ('work_experience_json', models.JSONField(blank=True, default=list)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_cv', to='api.application')),
                ('employee', models.ForeignKey(limit_choices_to={'role': 'employee'}, on_delete=django.db.models.deletion.CASCADE, related_name='generated_cvs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Generated CV',
                'verbose_name_plural': 'Generated CVs',
                'ordering': ['-generated_at'],
            },
        ),
    ]
