# Generated by Django 5.2.15 on 2026-06-29 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_generatedcv'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='external_apply_url',
            field=models.URLField(blank=True, help_text='Link to external company website for applying', max_length=1000, null=True),
        ),
    ]
