# Generated by Django 5.2.15 on 2026-07-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_customuser_email_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text="Email subject line shown in the recipient's inbox.", max_length=300)),
                ('body', models.TextField(help_text='Plain text body of the newsletter. Each new line becomes a paragraph in the email. No HTML needed — the system wraps it in the Quota Hire brand template automatically.')),
                ('audience', models.CharField(choices=[('employees', 'All Employees'), ('companies', 'All Companies'), ('all', 'All Users (Employees + Companies)')], default='all', help_text='Who should receive this newsletter?', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, help_text='Automatically set when the newsletter is dispatched.', null=True)),
                ('recipients_count', models.PositiveIntegerField(default=0, help_text='Number of emails successfully dispatched in the last send.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Newsletter',
                'verbose_name_plural': 'Newsletters',
                'ordering': ['-created_at'],
            },
        ),
    ]
