# Generated by Django 5.2.15 on 2026-07-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_add_newsletter_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='about_company',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='job',
            name='job_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
