# Generated by Django 5.2.15 on 2026-07-05 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_companyprofile_about_company_job_job_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='description',
        ),
        migrations.AddField(
            model_name='job',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
