# Generated by Django 5.2.15 on 2026-07-17 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_communitypoll_communitypollchoice_communitypost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypost',
            name='comments_disabled',
            field=models.BooleanField(default=False, help_text='Prevent others from commenting'),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='hide_likes',
            field=models.BooleanField(default=False, help_text='Hide like count from other users'),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='is_anonymous',
            field=models.BooleanField(default=False, help_text='Hide author name from other users'),
        ),
        migrations.CreateModel(
            name='CommunityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('inappropriate', 'Inappropriate Content'), ('misleading', 'Misleading Information'), ('harassment', 'Harassment or Bullying'), ('other', 'Other')], default='other', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='api.communitypost')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Community Report',
                'verbose_name_plural': 'Community Reports',
                'ordering': ['-created_at'],
                'unique_together': {('post', 'reporter')},
            },
        ),
    ]
