# Generated by Django — adds push_token to CustomUser for Expo push notifications

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_communitycomment_dislikes_communitycomment_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='push_token',
            field=models.CharField(
                blank=True,
                default=None,
                help_text='Expo push token for mobile push notifications',
                max_length=300,
                null=True,
            ),
        ),
    ]
