# Generated by Django 5.2.15 on 2026-07-30 09:48

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_add_password_reset_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('nature_of_business', models.CharField(blank=True, max_length=255)),
                ('contact_person_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Lead',
                'verbose_name_plural': 'Company Leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_needed_count', models.PositiveIntegerField(default=1)),
                ('role_title', models.CharField(max_length=255)),
                ('salary_budget', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('commission_structure', models.CharField(blank=True, max_length=255)),
                ('resumption_date', models.DateField(blank=True, null=True)),
                ('job_description', models.TextField(blank=True)),
                ('package_type', models.CharField(choices=[('RECRUITMENT_ONLY', 'Recruitment Only'), ('RECRUITMENT_PLUS_MANAGED', 'Recruitment + Managed Staffing')], default='RECRUITMENT_ONLY', max_length=50)),
                ('payment_status', models.CharField(choices=[('DEPOSIT_PAID', 'Deposit Paid'), ('FULL_PAYMENT', 'Full Payment'), ('PENDING', 'Pending')], default='PENDING', max_length=50)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('operational_status', models.CharField(choices=[('NEW_REQUEST', 'New Request'), ('IN_SOURCING', 'In Sourcing'), ('DEPLOYED', 'Deployed')], default='NEW_REQUEST', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Request',
                'verbose_name_plural': 'Company Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('OPERATIONAL', 'Operational'), ('MARKETING', 'Marketing'), ('COMMISSION', 'Commission'), ('SALARY_PAYROLL', 'Salary Payroll'), ('INFRASTRUCTURE', 'Infrastructure'), ('OTHER', 'Other')], default='OPERATIONAL', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('date_incurred', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('receipt_proof', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Expense Record',
                'verbose_name_plural': 'Expense Records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ManagedStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('gross_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('offer_letter_pdf', models.FileField(blank=True, null=True, upload_to='offer_letters/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Managed Staff',
                'verbose_name_plural': 'Managed Staff Roster',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayrollRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_year', models.CharField(max_length=20)),
                ('total_gross', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_net', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Payroll Record',
                'verbose_name_plural': 'Payroll Records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='passwordresetotp',
            new_name='api_passwor_user_id_868393_idx',
            old_name='api_passwo_user_id_is_used_idx',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('company', 'Company'), ('admin', 'Admin'), ('SALES_CAM', 'Sales CAM'), ('HR_OPS', 'HR Ops'), ('FINANCE_ADMIN', 'Finance Admin'), ('SUPERADMIN', 'Superadmin')], default='employee', max_length=20),
        ),
        migrations.AddField(
            model_name='companylead',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companyrequest',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='api.companylead'),
        ),
        migrations.AddField(
            model_name='expenserecord',
            name='logged_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logged_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='managedstaff',
            name='assigned_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_staff', to='api.companylead'),
        ),
        migrations.AddField(
            model_name='managedstaff',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='api.companyrequest'),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_records', to='api.companylead'),
        ),
    ]
