# Generated by Django 5.2.16 on 2026-08-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_companylead_companyrequest_expenserecord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='login_otp_code',
            field=models.CharField(blank=True, default='', help_text='6-digit OTP for passwordless login', max_length=6),
        ),
        migrations.AddField(
            model_name='customuser',
            name='login_otp_expires_at',
            field=models.DateTimeField(blank=True, help_text='When the login OTP expires (30 min window)', null=True),
        ),
    ]
