# Generated by Django 5.2.16 on 2026-09-11 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_hash_otp_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='package',
            field=models.CharField(blank=True, choices=[('promoted', 'Quota Hire Promoted Job'), ('pipeline', 'Quota Hire Pipeline'), ('hunters', 'Quota Hire Commission Hunters'), ('sales_ops', 'Quota Hire Sales Ops')], max_length=50),
        ),
    ]
