# Generated by Django 5.2.16 on 2026-09-12 03:01
"""Adds the community launch waitlist.

Only the new table. `makemigrations` also offered three unrelated operations
that had been left pending by earlier model edits — an index rename on
passwordresetotp, the widened role choices on customuser, and an index on
paymenttransaction.google_ack_failed. They were removed from this migration
rather than carried along with it, so this file does exactly one thing. That
drift is still outstanding and should get a migration of its own.
"""

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_job_package_promoted'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityWaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Stored lowercase so the same person cannot join twice.', max_length=254, unique=True)),
                ('source', models.CharField(default='mobile', help_text='Which client the person joined from.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notified_at', models.DateTimeField(blank=True, help_text='Set once the launch announcement has been sent to this address.', null=True)),
            ],
            options={
                'verbose_name': 'Community waitlist entry',
                'verbose_name_plural': 'Community waitlist',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='communitywaitlistentry',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Set when the request came from someone signed in.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_waitlist_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='communitywaitlistentry',
            index=models.Index(fields=['notified_at'], name='api_communi_notifie_ab1ec5_idx'),
        ),
    ]
